'use strict';
const test=require('node:test'),assert=require('node:assert/strict');const {createNotificationSystem}=require('../lib/order-notifications');const {createWecomClient}=require('../lib/wecom-client');
async function delivery({role='support',fail=false}={}){let queued=true,sends=0;const updates=[],config={id:1,enabled:1,corp_id:'fixture-corp',agent_id:1,corp_secret:'encrypted-fixture'};
 const n={id:1,user_id:3,kind:'support_message',title:'有新的客服咨询',order_ref:'11',order_type:'support',role,wecom_user_id:'fixture-support',corp_id:config.corp_id,agent_id:1,wecom_enabled:1,order_updates_enabled:0,created_at:new Date(Date.now()-48*3600000)};
 const conn={beginTransaction:async()=>{},commit:async()=>{},rollback:async()=>{},release(){},execute:async sql=>sql.startsWith('SELECT notification_id')?(queued?(queued=false,[[{notification_id:1}]]):[[]]):[{affectedRows:1}]};
 const pool={getConnection:async()=>conn,execute:async(sql,p)=>{if(sql.startsWith('SELECT * FROM wecom_notification_config'))return [[config]];if(sql.startsWith('SELECT n.*'))return [[n]];if(sql.startsWith('UPDATE notification_deliveries'))updates.push([sql,p]);return [{affectedRows:1}];}};
 await createNotificationSystem({pool,cipher:{decrypt:()=> 'fixture-secret'},siteUrl:'https://example.test',wecomClient:{send:async()=>{sends++;if(fail)throw Object.assign(Error('network'),{code:'WECOM_NETWORK'});return 'fixture-id';}}}).deliver();return {sends,updates};
}
test('support reminders deliver when staff is away, independently of order preferences and 24-hour order expiry',async()=>{assert.equal((await delivery()).sends,1);assert.equal((await delivery({role:'admin'})).sends,1);assert.equal((await delivery({role:'user'})).sends,0);});
test('support reminder provider failure persists an exponential retry and sanitized failure code',async()=>{const d=await delivery({fail:true});assert.equal(d.sends,1);assert.ok(d.updates.some(([sql,p])=>sql.includes("'failed','retry'")&&p[0]==='WECOM_NETWORK'));});
test('WeCom support links open the conversation and never include message body or game credentials',async()=>{let text;const c=createWecomClient({fetchImpl:async(url,o)=>new URL(url).pathname.endsWith('gettoken')?{ok:true,json:async()=>({access_token:'fixture-token'})}:{ok:true,json:async()=>{text=JSON.parse(o.body).text.content;return {errcode:0,msgid:'fixture-id'};}}});await c.send({corp_id:'fixturecorp',agent_id:1,secret:'fixturesecret'},'support_1',{kind:'support_message',order_type:'support',order_ref:'11',title:'有新的客服咨询',body:'有用户留言，请进入客服工作台处理。'},'https://example.test');assert.match(text,/support_chat=11/);assert.equal(text.includes('notify_order='),false);});
