'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),express=require('express');
const {createServiceContentRouter}=require('../routes/service-content'),{defaults}=require('../lib/service-content');
async function setup(t){let document=structuredClone(defaults),revision=1,audits=[],snapshot,fail=false;
 const execute=async(q,p)=>{if(q.startsWith('SELECT revision'))return [[{revision,document:JSON.stringify(document)}]];if(q.startsWith('UPDATE site_service_content')){document=JSON.parse(p[0]);revision++;return [{affectedRows:1}];}throw Error(q);};
 const conn={execute,beginTransaction:async()=>snapshot=structuredClone({document,revision,audits}),commit:async()=>{},rollback:async()=>{({document,revision,audits}=snapshot);},release(){}};
 const admin=(req,res,next)=>{if(!req.headers.authorization)return res.status(401).end();if(req.headers.authorization!=='Bearer admin')return res.status(403).end();req.userId=7;next();};
 const app=express();app.use(express.json());app.use(createServiceContentRouter({pool:{execute,getConnection:async()=>conn},adminMiddleware:admin,recordOperation:async(c,event)=>{assert.equal(c,conn);if(fail)throw Error('audit unavailable');audits.push(event);}}));const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));t.after(()=>{server.closeAllConnections();return new Promise(r=>server.close(r));});
 return {url:'http://127.0.0.1:'+server.address().port,document:()=>document,revision:()=>revision,audits:()=>audits,fail:()=>fail=true};}
const put=(s,field,body,role='admin')=>fetch(s.url+'/admin/service-content/'+field,{method:'PUT',headers:{'Content-Type':'application/json',...(role?{Authorization:'Bearer '+role}:{})},body:JSON.stringify(body)});
test('public reads omit drafts and admin writes require an actual administrator',async t=>{const s=await setup(t);const r=await fetch(s.url+'/service-content');assert.equal(r.status,200);assert.equal(r.headers.get('cache-control'),'no-store');assert.equal((await r.json()).projects.length,7);for(const role of [null,'user','booster'])assert.equal((await put(s,'projects',{revision:1,projects:defaults.projects},role)).status,role?403:401);});
test('catalog changes are versioned and audited; stale edits and audit failure do not persist',async t=>{const s=await setup(t),projects=structuredClone(defaults.projects);projects[0].options[0].price=9.8;assert.equal((await put(s,'projects',{revision:1,projects})).status,200);assert.equal(s.revision(),2);assert.equal(s.audits()[0].actorUserId,7);assert.equal((await put(s,'projects',{revision:1,projects})).status,409);assert.equal(s.revision(),2);s.fail();projects[0].options[0].price=10;assert.equal((await put(s,'projects',{revision:2,projects})).status,503);assert.equal(s.document().projects[0].options[0].price,9.8);assert.equal(s.revision(),2);assert.equal(s.audits().length,1);});
test('associated projects can be hidden but cannot be removed until the activity is unlinked',async t=>{const s=await setup(t),now=Date.now(),activity={id:'activity_1',kind:'platform',title:'活动',description:'说明',enabled:true,starts_at:new Date(now-1000).toISOString(),ends_at:new Date(now+100000).toISOString(),project_key:'silver',option_key:'a'};assert.equal((await put(s,'activities',{revision:1,activities:[activity]})).status,200);assert.equal((await put(s,'projects',{revision:2,projects:defaults.projects.slice(1)})).status,400);const projects=structuredClone(defaults.projects);projects[0].enabled=false;assert.equal((await put(s,'projects',{revision:2,projects})).status,200);assert.equal((await (await fetch(s.url+'/service-content')).json()).activities[0].can_order,false);});
