'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),express=require('express');const {createPermissionsRouter}=require('../routes/user-permissions');
async function fixture(t){let users=[{id:1,username:'owner',role:'admin',token_version:0},{id:2,username:'客服候选',role:'user',token_version:0}],snapshot,auditFail=false;const queries=[];
 const execute=async(sql,p)=>{queries.push([sql,p]);if(sql.startsWith('SELECT COUNT'))return [[{total:2}]];if(sql.startsWith('SELECT id,username'))return [users];if(sql.startsWith('SELECT id,role'))return [users.filter(u=>u.role==='admin'||u.id===p[0])];if(sql.startsWith('UPDATE users')){const u=users.find(u=>u.id===p[1]);u.role=p[0];u.token_version++;return [{affectedRows:1}];}throw Error(sql);};
 const pool={execute,getConnection:async()=>({execute,beginTransaction:async()=>snapshot=structuredClone(users),commit:async()=>{},rollback:async()=>users=snapshot,release(){}})};const app=express();app.use(express.json());app.use('/users',createPermissionsRouter({pool,adminMiddleware:(req,res,next)=>{req.userId=Number(req.headers.authorization)||1;if(users.find(u=>u.id===req.userId)?.role!=='admin')return res.status(403).json({error:'admin required'});next();},recordOperation:async()=>{if(auditFail)throw Error('failed');}}));const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));t.after(()=>new Promise(r=>server.close(r)));
 return {users:()=>users,queries,failAudit:()=>auditFail=true,request:(p,body,user=1)=>fetch(`http://127.0.0.1:${server.address().port}/users${p}`,{method:body?'PUT':'GET',headers:{Authorization:String(user),'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})})};
}
test('only admins can manage permissions; staff assignment revokes old sessions and prevents stale writes',async t=>{const f=await fixture(t);assert.equal((await f.request('/2/role',{role:'support',expected_role:'user'},2)).status,403);assert.equal((await f.request('/2/role',{role:'support',expected_role:'user'})).status,200);assert.equal(f.users()[1].role,'support');assert.equal(f.users()[1].token_version,1);assert.equal((await f.request('/2/role',{role:'admin',expected_role:'user'})).status,409);assert.equal((await f.request('/1/role',{role:'user',expected_role:'admin'})).status,409);});
test('search is parameterized and paginated; audit failure rolls back privilege changes',async t=>{const f=await fixture(t);assert.equal((await f.request('?q=%25_%27&role=support&page=2')).status,200);const q=f.queries.find(([sql])=>sql.startsWith('SELECT id,username'));assert.ok(q[0].includes('LIMIT 20 OFFSET 20'));assert.equal(q[1][0],"%\\%\\_'%");f.failAudit();assert.equal((await f.request('/2/role',{role:'admin',expected_role:'user'})).status,503);assert.equal(f.users()[1].role,'user');assert.equal(f.users()[1].token_version,0);});
